spring:
  application:
    name: kafka-training
  datasource:
    url: jdbc:postgresql://localhost:5432/develop
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: "localhost:9093"
    admin:
      auto-create: true   #por defecto es true es decir crea los topicos automaticamente
      client-id: kafka-training
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: SALES-GROUP
      properties:
        spring.json.value.default.type: "co.example.kafkatraining.infrastructure.kafka.schemas.SaleSchema"
        spring.json.trusted.packages: "co.example.kafkatraining.infrastructure.kafka.schemas"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
    listener:
      ack-mode: record     #por defecto es en BATCH


